import { wordNoteTemplates } from "./wordNoteTemplates";

const requiredWordNoteTemplateFallbacks = {
  "1EnToFaKnowingFilter": {
    Front: `{{base_form}}`,
    Back: `{{meaning_fa}}`,
  },
  "1FaToEnKnowingFilter": {
    Front: `{{meaning_fa}}`,
    Back: `{{base_form}}`,
  },
} as const;

export const WordAnkiConstants = {
  noteFields: [
    "anki_link_id",
    "base_form",
    "base_form_audio",
    "first-part-spell",
    "first-part-spell-audio",
    "phonetic_us",
    "pos",
    "meaning_fa",
    "meaning_fa_audio",
    "other_meanings_fa",
    "other_meanings_fa_audio",
    "other_meanings_en",
    "other_meanings_en_audio",
    "concept_explained_fa",
    "concept_explained_fa_audio",
    "sentence_en",
    "sentence_en_audio",
    "sentence_en_meaning_fa",
    "sentence_en_meaning_fa_audio",
    "best_translate",
    "mixed_sentence",
    "first_letter_fa_hint",
    "first_letter_en_hint",
    "selfGuide",
    "hint_to_select_letters",
    "hint_sentence",
    "phonetic_us_normalized",
    "learning_depth",
    "imageability",
    "json_hint",
    "updatedAt",
  ],
  noteTemplates: {
    ...requiredWordNoteTemplateFallbacks,
    ...wordNoteTemplates,
  },
  cardTypes: {
    EnToFa: "EnToFa",
    EnToFaKnowingFilter: "1EnToFaKnowingFilter",
    EnToFaRev: "EnToFaRev",
    FaToEn: "FaToEn",
    FaToEnKnowingFilter: "1FaToEnKnowingFilter",
    FaToEnRev: "FaToEnRev",
    Emla: "Emla",
    Rahnama: "Rahnama",
    Rahnama2: "Rahnama2",
  },
  decks: {
    default: "Default",
    tempRoot: "TempFor1WordsForNewStudy",
    root: "WordsForNewStudy",
    EnToFa: "WordsForNewStudy::EnToFa",
    EnToFaKnowingFilter: "WordsForNewStudy::1EnToFaKnowingFilter",
    EnToFaRev: "WordsForNewStudy::EnToFaRev",
    FaToEn: "WordsForNewStudy::FaToEn",
    FaToEnKnowingFilter: "WordsForNewStudy::1FaToEnKnowingFilter",
    FaToEnRev: "WordsForNewStudy::FaToEnRev",
    Emla: "WordsForNewStudy::Emla",
    Rahnama: "WordsForNewStudy::Rahnama",
    Rahnama2: "WordsForNewStudy::Rahnama2",
  },
} as const;
